# Generated by Django 5.0 on 2024-03-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
                ('age', models.IntegerField(max_length=3)),
                ('gender', models.BooleanField(default=True)),
                ('photo', models.ImageField(upload_to='images')),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
