# Generated by Django 5.0 on 2024-04-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='images')),
                ('total', models.IntegerField()),
            ],
        ),
    ]
